Add user input to choose install for simulation only or full setup with robot

diff --git a/movo_remote_pc_setup/setup_remote_pc b/movo_remote_pc_setup/setup_remote_pc
--- a/movo_remote_pc_setup/setup_remote_pc
+++ b/movo_remote_pc_setup/setup_remote_pc
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-echo -e "This script assumes that you have ubuntu 14.04.5LTS installed.\n\n It is OK to have already installed ROS this will add any missing components.\n\n Please understand that this script modifies the environment and sets everything up to connect to a Movo robot\n"
+echo -e "This script assumes that you have ubuntu 14.04.5LTS installed.\n\n It is OK to have already installed ROS this will add any missing components.\n\n Please understand that this script modifies the environment and sets simulation requirement for Movo Robot. It is not adequant to use this setup to connect to a Movo robot\n"
 
 read -r -p "Are you absolutely sure you want to continue? [y/N] " response
 if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
@@ -19,44 +19,6 @@ echo "$USER ALL=(ALL) NOPASSWD:ALL" | (sudo su -c 'EDITOR="tee -a" visudo') >> /
 temp=1
 temp1=1
 cnts=0
-while [ $cnts -lt 10 ]; do
-    echo -e "\nPlease connect to the robot via ethernet cable\nand to the internet another interface\n\nPress any key to continue....\n"
-    read -n 1 -s
-    ping -q -c 1 -W 1 10.66.171.1 >/dev/null
-    temp=$?
-    ping -q -c 1 -W 1 10.66.171.2 >/dev/null
-    temp1=$?
-    ping -q -c 1 -W 1 8.8.8.8 >/dev/null
-    temp2=$?
-    cnts=$[$cnts+1]
-    echo "$temp $temp1 $temp2"
-    if [ $temp -eq 0 ] && [ $temp1 -eq 0 ] && [ $temp2 -eq 0 ]; then
-      cnts=10
-      echo "Success"
-      break
-    fi
-
-    if [ $temp -ne 0 ]; then
-      echo "Unable to ping movo2, no robot connection....trying again."
-    fi
-    if [ $temp1 -ne 0 ]; then
-      echo "Unable to ping movo1, no robot connection....trying again."
-    fi    
-    if [ $temp2 -ne 0 ]; then
-      echo "Unable to ping Google DNS, no internet connection....trying again."
-    fi
-done 
-
-if [ $temp -ne 0 ] || [ $temp1 -ne 0 ]; then
-  echo "Robot Connection timed out, try again....exiting"
-  sleep 2
-  exit 1
-fi
-if [ $temp2 -ne 0 ]; then
-  echo "Internet Connection timed out, try again....exiting"
-  sleep 2
-  exit 1
-fi
 
 sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
 sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
@@ -99,18 +61,67 @@ then
     rm -rf libfreenect2
 fi
 
+if grep -q "MOVO REMOTE PC START" ~/.bashrc
+then
+    echo ".bashrc is already updated for movo remote"
+else
+    cat config/bash_rc_partial >> ~/.bashrc
+fi
+
+read -r -p "Do you want to setup only for simulation, in case you do not have a Movo Robot available [y/N]" response
+if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
+then
+    source ~/.bashrc
+    echo -e "\nScript has finished configuring the remote PC for simulation.\n\nPress any key to continue....\n"
+    read -n 1 -s
+    exit 1
+fi
+
+while [ $cnts -lt 10 ]; do
+    echo -e "\nPlease connect to the robot via ethernet cable\nand to the internet another interface\n\nPress any key to continue....\n"
+    read -n 1 -s
+    ping -q -c 1 -W 1 10.66.171.1 >/dev/null
+    temp=$?
+    ping -q -c 1 -W 1 10.66.171.2 >/dev/null
+    temp1=$?
+    ping -q -c 1 -W 1 8.8.8.8 >/dev/null
+    temp2=$?
+    cnts=$[$cnts+1]
+    echo "$temp $temp1 $temp2"
+    if [ $temp -eq 0 ] && [ $temp1 -eq 0 ] && [ $temp2 -eq 0 ]; then
+      cnts=10
+      echo "Success"
+      break
+    fi
+
+    if [ $temp -ne 0 ]; then
+      echo "Unable to ping movo2, no robot connection....trying again."
+    fi
+    if [ $temp1 -ne 0 ]; then
+      echo "Unable to ping movo1, no robot connection....trying again."
+    fi    
+    if [ $temp2 -ne 0 ]; then
+      echo "Unable to ping Google DNS, no internet connection....trying again."
+    fi
+done 
+
+if [ $temp -ne 0 ] || [ $temp1 -ne 0 ]; then
+  echo "Robot Connection timed out, try again....exiting"
+  sleep 2
+  exit 1
+fi
+if [ $temp2 -ne 0 ]; then
+  echo "Internet Connection timed out, try again....exiting"
+  sleep 2
+  exit 1
+fi
+
 if grep -q "movo1" /etc/hosts
 then
     echo "movo1 and movo2 are already defined in /etc/hosts"
 else
     sudo sed -i "/127.0.1.1/a 10.66.171.2 movo1" /etc/hosts 
     sudo sed -i "/10.66.171.2 movo1/a 10.66.171.1 movo2" /etc/hosts
-fi
-if grep -q "MOVO REMOTE PC START" ~/.bashrc
-then
-    echo ".bashrc is already updated for movo remote"
-else
-    cat config/bash_rc_partial >> ~/.bashrc
 fi
 
 if [ ! -f ~/.ssh/id_rsa.pub ]; then
